### ISSUE TITLE
np.random.choice doesn't want a to be empty

### ISSUE THREAD

**Issue by pranavdogra7** [eliorc/node2vec#1]
`              if source in sampling_strategy:
                    walk_length = sampling_strategy[source].get(walk_length_key, global_walk_length)
                else:
                    walk_length = global_walk_length

                while len(walk) < walk_length:
                    walk_options = d_graph[walk[-1]][neighbors_key]
                    
                    if len(walk) == 1:  # For the first step
                        walk_to = np.random.choice(walk_options, size=1)[0]
                    else:
                        probabilities = d_graph[walk[-1]][probabilities_key][walk[-2]]
                        walk_to = np.random.choice(walk_options, size=1, p=probabilities)[0]

                    walk.append(walk_to)`

This is giving error. Can you please look into it ?

**Comment by pranavdogra7** [comment]
Here's the error I'm getting
`/Users/rambo/anaconda3/lib/python3.6/site-packages/node2vec/node2vec.py in parallel_generate_walks(d_graph=defaultdict(<class 'dict'>, {'0': {'probabilitie...7': array([], dtype=float64)}, 'neighbors': []}}), global_walk_length=30, num_walks=50, cpu_num=1, sampling_strategy={}, num_walks_key='num_walks', walk_length_key='walk_length', neighbors_key='neighbors', probabilities_key='probabilities')
     48                 if source in sampling_strategy:
     49                     walk_length = sampling_strategy[source].get(walk_length_key, global_walk_length)
     50                 else:
     51                     walk_length = global_walk_length
     52                     
---> 53                 logging.warning('walk_length : %s', walk_length)
        walk_length = 30
     54 
     55                 while len(walk) < walk_length:
     56                     walk_options = d_graph[walk[-1]][neighbors_key]
     57                     logging.warning('walk_options : %s', walk_options)

...........................................................................
/Users/rambo/anaconda3/lib/python3.6/site-packages/numpy/random/mtrand.cpython-36m-darwin.so in mtrand.RandomState.choice()

ValueError: a must be non-empty`

**Comment by pranavdogra7** [comment]
Still the same error

/Users/rambo/anaconda3/lib/python3.6/site-packages/node2vec/node2vec.py in parallel_generate_walks(d_graph=defaultdict(<class 'dict'>, {'0': {'probabilitie...7': array([], dtype=float64)}, 'neighbors': []}}), global_walk_length=30, num_walks=50, cpu_num=1, sampling_strategy={}, num_walks_key='num_walks', walk_length_key='walk_length', neighbors_key='neighbors', probabilities_key='probabilities')
     48                     if neighbors_key not in d_graph[walk[-1]]:
     49                         break
     50                     else:
     51                         walk_options = d_graph[walk[-1]][neighbors_key]
     52                     if len(walk) == 1:  # For the first step
---> 53                         walk_to = np.random.choice(walk_options, size=1)[0]
        walk_to = '187'
        walk_options = []
     54                     else:
     55                         probabilities = d_graph[walk[-1]][probabilities_key][walk[-2]]
     56                         walk_to = np.random.choice(walk_options, size=1, p=probabilities)[0]
     57                     walk.append(walk_to)

...........................................................................
/Users/rambo/anaconda3/lib/python3.6/site-packages/numpy/random/mtrand.cpython-36m-darwin.so in mtrand.RandomState.choice()

ValueError: a must be non-empty

**Comment by pranavdogra7** [comment]
The extra thing you should know is I had a neo4j graph database, and I converted that to networkx and then after I proceeded with your code.

**Comment by eliorc** [comment]
I'll work on it soon

**Comment by pranavdogra7** [comment]
Ok, thanks for the help

**Comment by eliorc** [comment]
Can you try switching this

```
    # Perform walk
    while len(walk) < walk_length:
```

with this

```
# Skip nodes without neighbors
if neighbors_key in d_graph[walk[-1]] and d_graph[walk[-1]][neighbors_key]:

    # Perform walk
    while len(walk) < walk_length:
```

(Please make sure you use the changed code)

**Comment by eliorc** [comment]
Can you change 

```
walk_options = d_graph[walk[-1]][neighbors_key]
```

to this

walk_options = d_graph[walk[-1]][neighbors_key]
```
# Skip dead end nodes
if not walk_options:
    break
```

And report results?

**Comment by pranavdogra7** [comment]
Still the same issue. I have tried basic checks, with length and exception handling, it's still giving the same error

**Comment by eliorc** [comment]
To debug this correctly I'll need you to give me a way to reproduce the nx.Graph, and the calling code to the node2vec functions

**Comment by pranavdogra7** [comment]
[export.txt](https://github.com/eliorc/node2vec/files/1954808/export.txt)

I exported my graph as json and have attached the file(just change the extension to json), and here's how you can [reproduce](https://stackoverflow.com/questions/34665042/read-json-graph-networkx-file) it. For calling node2vec, I just followed your methods.

**Comment by eliorc** [comment]
Thanks, I'll look into it

**Comment by eliorc** [comment]
@pranavdogra7 Given the file and the SO post, I run this code and it fails
```
def read_json_file(filename):
    with open(filename) as f:
        js_graph = json.load(f)
    return nx.readwrite.json_graph.node_link_graph(js_graph)

graph = read_json_file(JSON_FILE)
```

I get the following error:

> Traceback (most recent call last):
>  File "/home/elior/Code/VirtualEnvs/node2vec/lib/python3.6/site->packages/IPython/core/interactiveshell.py", line 2910, in run_code
>    exec(code_obj, self.user_global_ns, self.user_ns)
>  File "<ipython-input-13-7965861da755>", line 8, in <module>
>    graph = read_json_file(JSON_FILE)
>  File "<ipython-input-13-7965861da755>", line 6, in read_json_file
>    return nx.readwrite.json_graph.node_link_graph(js_graph)
>  File "/home/elior/Code/VirtualEnvs/node2vec/lib/python3.6/site->packages/networkx/readwrite/json_graph/node_link.py", line 173, in node_link_graph
>    for d in data[links]:
>KeyError: 'links'

Running networkx version 2.0

**Comment by pranavdogra7** [comment]
[export - Copy.txt](https://github.com/eliorc/node2vec/files/1958311/export.-.Copy.txt)
Okay, try with this file.
Here's the code to load the graph
`with open("export - Copy.json") as file:
	g = json.load(file)

graph = json_graph.node_link_graph(g)

# you can view it 
# nx.draw(graph)`

**Comment by pranavdogra7** [comment]
With the previous file (case 1), you can use the below-mentioned code
```python
with open("export.json") as file:
	g = json.load(file)

graph = json_graph.adjacency_graph(g)
nx.draw(graph)
```

**Comment by eliorc** [comment]
@pranavdogra7 , I believe this is fixed, please update your node2vec version to the lastest (0.1.2) and report if this was solved. Thanks
