### ISSUE TITLE
ValueError: probabilities contain NaN

### ISSUE THREAD

**Issue by davidfstein** [eliorc/node2vec#53]
Trying run node2vec on my dataset using the example code from the ReadMe. During the walk generation, I am receiving the following error: 

```
File "mtrand.pyx", line 920, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN
```
Any idea where this is coming from? My dataset is ~ 120 MB, but I can provide it if helpful

**Comment by eliorc** [comment]
Hi @davidfstein, can you include the full stacktrace? I need to see where is the last line inside `node2vec` that generates this error

**Comment by davidfstein** [comment]
Sorry the formatting is weird. I had to run with nohup and tqdm doesn't right to files very nicely. 
```
File "n2v.py", line 14, in <module>
    rep = Node2Vec(g, dimensions=64, walk_length=30, num_walks=200, workers=30, temp_folder="/home/itan_lab/david/")
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/node2vec/node2vec.py", line 67, in __init__
File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/node2vec/node2vec.py", line 154, in _generate_walks
in enumerate(num_walks_lists, 1))
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/joblib/parallel.py", line 1042, in __call__
 self.retrieve()
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/joblib/parallel.py", line 921, in retrieve
 self._output.extend(job.get(timeout=self.timeout))
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
return self.func(*args, **kwargs)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/joblib/parallel.py", line 253, in __call__
for func, args, kwargs in self.items]
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/node2vec/parallel.py", line 60, in parallel_generate_walks
walk_to = np.random.choice(walk_options, size=1, p=probabilities)[0]
  File "mtrand.pyx", line 920, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN
```
I am using edge weights. Here is my script: 
```
import pandas as pd
import networkx as nx
from node2vec import Node2Vec

g = nx.Graph()

connectome = pd.read_csv('rel_fusion.csv')

connectome.columns = ['protein1', 'protein2', 'score']

for index, row in connectome.iterrows():
    g.add_edge(row['protein1'], row['protein2'], weight=float(row['score']))

rep = Node2Vec(g, dimensions=64, walk_length=30, num_walks=200, workers=30, temp_folder="/home/itan_lab/david/")

# Embed nodes
model = rep.fit(window=10, min_count=1, batch_words=4)
# Any keywords acceptable by gensim.Word2Vec can be passed, `diemnsions` and `workers` are automatically passed (from the Node2Vec constructor)

# Look for most similar nodes
# model.wv.most_similar('2')  # Output node names are always strings

# Save embeddings for later use
model.wv.save_word2vec_format('fusion.emb')

# Save model for later use
model.save('fusion_n2v_model.txt')
```

**Comment by eliorc** [comment]
Seems like some scores are NaN, can you check that? Run `connectme.isnull().sum()` and see if you have NaNs in the `score` column. If you do, deal with them and try to run the code again

**Comment by davidfstein** [comment]
That's what I figured at first but there are no NaNs:
```
c.isnull().sum()
g1       0
g2       0
score    0
dtype: int64
```
There is also this warning during the transition probabilities stage:
```
/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/node2vec/node2vec.py:116: RuntimeWarning: invalid value encountered in true_divide
  source] = unnormalized_weights / unnormalized_weights.sum()
/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/node2vec/node2vec.py:125: RuntimeWarning: invalid value encountered in true_divide
  d_graph[source][self.FIRST_TRAVEL_KEY] = first_travel_weights / first_travel_weights.sum()
```
I should have included it to begin with. Maybe its related?

**Comment by eliorc** [comment]
Really weird, can you give me the code to reproduce? I'll need the data as well.

If not, I want to isolate the problem, can you please try the same code without the `weight` assignment?

**Comment by davidfstein** [comment]
I recreated the issue with a small subset that I'll attach here. 
The code:
```
import pandas as pd
import networkx as nx
from node2vec import Node2Vec

g = nx.Graph()

connectome = pd.read_csv('test_data.csv')

connectome.columns = ['protein1', 'protein2', 'score']

for index, row in connectome.iterrows():
    g.add_edge(row['protein1'], row['protein2'], weight=float(row['score']))

rep = Node2Vec(g, dimensions=64, walk_length=30, num_walks=200, workers=30, temp_folder="/home/itan_lab/david/")

# Embed nodes
model = rep.fit(window=10, min_count=1, batch_words=4)
# Any keywords acceptable by gensim.Word2Vec can be passed, `diemnsions` and `workers` are automatically passed (from the Node2Vec constructor)

# Look for most similar nodes
# model.wv.most_similar('2')  # Output node names are always strings

# Save embeddings for later use
model.wv.save_word2vec_format('fusion.emb')

# Save model for later use
model.save('fusion_n2v_model.txt')
```
The output:
```
Computing transition probabilities:   0%|                                                                                                                                             | 0/766 [00:00<?, ?it/s]/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/node2vec/node2vec.py:116: RuntimeWarning: invalid value encountered in true_divide
  source] = unnormalized_weights / unnormalized_weights.sum()
/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/node2vec/node2vec.py:125: RuntimeWarning: invalid value encountered in true_divide
  d_graph[source][self.FIRST_TRAVEL_KEY] = first_travel_weights / first_travel_weights.sum()
Computing transition probabilities: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 766/766 [00:00<00:00, 2097.16it/s]
Generating walks (CPU: 1):   0%|                                                                                                                                                        | 0/7 [00:00<?, ?it/sTraceback (most recent call last):                                                                                                                                                       | 0/7 [00:00<?, ?it/s]
  File "n2v.py", line 14, in <module>                                                                                                                                                   | 0/7 [00:00<?, ?it/s]
    rep = Node2Vec(g, dimensions=64, walk_length=30, num_walks=200, workers=30, temp_folder="/home/itan_lab/david/")                                                                    | 0/7 [00:00<?, ?it/s]
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/node2vec/node2vec.py", line 67, in __init__                                                                 | 0/7 [00:00<?, ?it/s]
    self.walks = self._generate_walks()                                                                                                                                                 | 0/7 [00:00<?, ?it/s]
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/node2vec/node2vec.py", line 154, in _generate_walks                                                         | 0/7 [00:00<?, ?it/s]
    in enumerate(num_walks_lists, 1))                                                                                                                                                   | 0/7 [00:00<?, ?it/s]
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/joblib/parallel.py", line 1042, in __call__                                                                 | 0/7 [00:00<?, ?it/s]
    self.retrieve()PU: 8):   0%|                                                                                                                                                        | 0/7 [00:00<?, ?it/s]
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/joblib/parallel.py", line 921, in retrieve                                                                  | 0/7 [00:00<?, ?it/s]
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/node2vec/parallel.py", line 60, in parallel_generate_walks
    walk_to = np.random.choice(walk_options, size=1, p=probabilities)[0]
  File "mtrand.pyx", line 920, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN
Generating walks (CPU: 1):  14%|████████████████████▌                                                                                                                           | 1/7 [00:00<00:00,  6.26it/s]
Generating walks (CPU: 11):  14%|████████████████████▍                                                                                                                          | 1/7 [00:00<00:00,  6.67it/s]
Generating walks (CPU: 8):  14%|████████████████████▌                                                                                                                           | 1/7 [00:00<00:00,  6.64it/s]
Generating walks (CPU: 10):  14%|████████████████████▍                                                                                                                          | 1/7 [00:00<00:00,  6.60it/s]
Generating walks (CPU: 5):  14%|████████████████████▌                                                                                                                           | 1/7 [00:00<00:00,  6.56it/s]
Generating walks (CPU: 9):  14%|████████████████████▌                                                                                                                           | 1/7 [00:00<00:00,  6.51it/s]
Generating walks (CPU: 7):  14%|████████████████████▌                                                                                                                           | 1/7 [00:00<00:00,  6.47it/s]
Generating walks (CPU: 6):  14%|████████████████████▌                                                                                                                           | 1/7 [00:00<00:00,  6.42it/s]
Generating walks (CPU: 4):  14%|████████████████████▌                                                                                                                           | 1/7 [00:00<00:00,  6.38it/s]
Generating walks (CPU: 3):  14%|████████████████████▌                                                                                                                           | 1/7 [00:00<00:00,  6.31it/s]
Generating walks (CPU: 2):  14%|████████████████████▌   
```
[data.zip](https://github.com/eliorc/node2vec/files/5612869/data.zip)

**Comment by eliorc** [comment]
@davidfstein I figured out the problem - the problem is that most of your weights are zero.
In the algorithm node2vec, weights cannot be zero - because weights (after normalization) are treated as walk probabilities, so essentially using the weights you can control how strongly two nodes are connected.

Zero edge weight is essentially no edge, so you cannot use zero weights. So before applying node2vec, depending on your use case decide what to do with the zero weights, you can either train without weights, or decide anything else that serves your problem - as long as you avoid assigning zero weights.

Thanks for this issue, I will make sure in the next version to give a better error message for zero weights

**Comment by davidfstein** [comment]
That makes sense. Thanks @eliorc!
